server:
  port: 7777
  servlet:
    context-path: /scala-boot

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/imoocbootscala
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql